name = input ("กรุณากรอกชื่่อ\n  ")
nickname =input("กรุณาใส่ชื่อเล่น\n ")
age =input("กรุณาใส่อายุ\n ")
id= input("กรุณาใส่รหัสประจำตัว\n ")
study= input("กรุณาใส่ชั้นปี\n")
hight= int(input("กรุณาใส่ส่วนสูง\n"))
weigth=int(input("กรุณาใส่น้ำหนัก\n"))
a =hight+weigth
print("ประวัติย่อ")
print("ชื่อ: "+ name + "อายุ"+ age +"ปี")
print("รหัสประจำตัวนักเรียน: "+ id + "ชั้นปี"+ study)
print("ชื่อเล่น: "+ nickname)
print("ส่วนสูง: "+ str(hight) + "เซนติเมตร" + "น้ำหนัก"+str(weigth) + "กิโลกรัม")
print("ส่วนสูง+น้ำหนัก =" + str(a))