name = input ("กรุณากรอกชื่่อ\n  ")
nickname =input("กรุณาใส่ชื่อเล่น\n ")
age =input("กรุณาใส่อายุ\n ")
id= input("กรุณาใส่รหัสประจำตัว\n ")
study= input("กรุณาใส่ชั้นปี\n")
hight= int(input("กรุณาใส่ส่วนสูง\n"))
weigth=int(input("กรุณาใส่น้ำหนัก\n"))
a =hight+weigth
print("ประวัติย่อ")
print(f"ชื่อ: + {name} อายุ: {age} +ปี")
print(f"รหัสประจำตัวนักเรียน: {id} ชั้นปี: {study}")
print(f"ชื่อเล่น : {nickname}")
print(f"ส่วนสูง: {hight} น้ำหนัก {weigth}")
print(f"{a} x {}")